<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\Product\Persistence\Models\Product;
use App\Modules\Product\Persistence\Models\ProductBarcode;
use App\Modules\Category\Persistence\Models\Category;
use App\Modules\Brand\Persistence\Models\Brand;
use App\Modules\Unit\Persistence\Models\Unit;
use App\Modules\Inventory\Persistence\Models\Stock;
use App\Modules\Settings\Persistence\Models\SysStatus;
use App\Modules\Warehouse\Persistence\Models\Warehouse;

class ProductCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $activeStatusId = SysStatus::where('domain', 'SYSTEM')->where('code', 'ACTIVE')->value('id') ?? 1;
        $warehouse = Warehouse::first();

        // 1. Ensure Categories
        $categoriesData = [
            ['code' => 'CAT-BEV', 'name' => 'Beverages & Soft Drinks', 'description' => 'Refreshing carbonated drinks, juices, energy drinks, and mineral waters'],
            ['code' => 'CAT-SNK', 'name' => 'Snacks & Confectionery', 'description' => 'Chips, crisps, chocolates, candy, biscuits, and nuts'],
            ['code' => 'CAT-COF', 'name' => 'Coffee & Tea Specialties', 'description' => 'Gourmet coffee beans, ground coffee, tea leaves, and cafe essentials'],
            ['code' => 'CAT-DAI', 'name' => 'Dairy & Chilled Foods', 'description' => 'Fresh milk, artisan cheeses, yogurts, and butter'],
            ['code' => 'CAT-GRO', 'name' => 'Pantry & Grocery Essentials', 'description' => 'Pasta, sauces, olive oils, seasonings, canned goods, and grains'],
            ['code' => 'CAT-ELE', 'name' => 'Consumer Electronics & Gadgets', 'description' => 'Smart accessories, headphones, audio, cables, and wearables'],
            ['code' => 'CAT-HEA', 'name' => 'Personal Care & Health', 'description' => 'Skincare, dental hygiene, hair care, and wellness products'],
            ['code' => 'CAT-HOM', 'name' => 'Home, Kitchen & Living', 'description' => 'Kitchen appliances, drinkware, storage, and home accessories'],
            ['code' => 'CAT-APP', 'name' => 'Apparel & Lifestyle', 'description' => 'Sportswear, casual t-shirts, caps, and lifestyle gear'],
            ['code' => 'CAT-OFF', 'name' => 'Stationery & Office Supplies', 'description' => 'Notebooks, premium pens, desk organizers, and paper goods'],
        ];

        $categories = [];
        foreach ($categoriesData as $c) {
            $categories[$c['code']] = Category::firstOrCreate(
                ['code' => $c['code']],
                array_merge($c, ['status_id' => $activeStatusId])
            );
        }

        // 2. Ensure Brands
        $brandsData = [
            ['code' => 'BR-COCA', 'name' => 'Coca-Cola Company', 'description' => 'Global leader in carbonated soft drinks and beverages'],
            ['code' => 'BR-PEPSI', 'name' => 'PepsiCo', 'description' => 'Multinational food, snack, and beverage corporation'],
            ['code' => 'BR-NESTLE', 'name' => 'Nestle', 'description' => 'Swiss multinational food and drink processing conglomerate'],
            ['code' => 'BR-LAYS', 'name' => 'Lays Frito-Lay', 'description' => 'World-famous crispy potato chips and savoury snacks'],
            ['code' => 'BR-REDBULL', 'name' => 'Red Bull', 'description' => 'Iconic premium functional energy drinks'],
            ['code' => 'BR-STARBUCKS', 'name' => 'Starbucks Coffee', 'description' => 'World-renowned roasted arabica coffee and specialty blends'],
            ['code' => 'BR-APPLE', 'name' => 'Apple Inc.', 'description' => 'Premium electronics, smartphones, and computer accessories'],
            ['code' => 'BR-SAMSUNG', 'name' => 'Samsung Electronics', 'description' => 'Cutting-edge consumer tech, displays, and smart devices'],
            ['code' => 'BR-SONY', 'name' => 'Sony Corporation', 'description' => 'Audio excellence, wireless headphones, and entertainment gear'],
            ['code' => 'BR-ANKER', 'name' => 'Anker Innovations', 'description' => 'High-speed chargers, power banks, and cable accessories'],
            ['code' => 'BR-LOGITECH', 'name' => 'Logitech', 'description' => 'Ergonomic computer peripherals, mice, and keyboards'],
            ['code' => 'BR-NIKE', 'name' => 'Nike Sportswear', 'description' => 'World-class athletic footwear, apparel, and accessories'],
            ['code' => 'BR-ADIDAS', 'name' => 'Adidas Originals', 'description' => 'Iconic German three-stripe athletic and lifestyle clothing'],
            ['code' => 'BR-LOREAL', 'name' => 'LOreal Paris', 'description' => 'World leader in beauty, cosmetics, and professional skincare'],
            ['code' => 'BR-NIVEA', 'name' => 'Nivea Beiersdorf', 'description' => 'Trusted gentle skin hydration, body wash, and daily care'],
            ['code' => 'BR-BARILLA', 'name' => 'Barilla Italy', 'description' => 'Authentic Italian durum wheat pasta and pasta sauces'],
            ['code' => 'BR-PHILIPS', 'name' => 'Philips Home', 'description' => 'Innovative domestic appliances, grooming, and lighting'],
            ['code' => 'BR-MOLESKINE', 'name' => 'Moleskine', 'description' => 'Legendary notebooks, journals, and creative writing gear'],
            ['code' => 'BR-LINDT', 'name' => 'Lindt and Sprungli', 'description' => 'Master Swiss chocolatiers creating silky chocolate truffles'],
            ['code' => 'BR-SANPELLEGRINO', 'name' => 'San Pellegrino', 'description' => 'Sparkling Italian natural mineral water and citrus sodas'],
            ['code' => 'BR-TWININGS', 'name' => 'Twinings of London', 'description' => 'Historic British tea maker blending classic English teas'],
            ['code' => 'BR-SCHWEPPES', 'name' => 'Schweppes', 'description' => 'Original tonic water and sparkling mixers since 1783'],
        ];

        $brands = [];
        foreach ($brandsData as $b) {
            $brands[$b['code']] = Brand::firstOrCreate(
                ['code' => $b['code']],
                array_merge($b, ['status_id' => $activeStatusId])
            );
        }

        // 3. Ensure Units
        $unitsData = [
            ['code' => 'PCS', 'name' => 'Piece', 'symbol' => 'pc', 'decimal_places' => 0],
            ['code' => 'CAN', 'name' => 'Can', 'symbol' => 'can', 'decimal_places' => 0],
            ['code' => 'BTL', 'name' => 'Bottle', 'symbol' => 'btl', 'decimal_places' => 0],
            ['code' => 'PCK', 'name' => 'Pack', 'symbol' => 'pck', 'decimal_places' => 0],
            ['code' => 'BOX', 'name' => 'Box', 'symbol' => 'box', 'decimal_places' => 0],
            ['code' => 'CTN', 'name' => 'Carton', 'symbol' => 'ctn', 'decimal_places' => 0],
            ['code' => 'KG', 'name' => 'Kilogram', 'symbol' => 'kg', 'decimal_places' => 2],
            ['code' => 'SET', 'name' => 'Set', 'symbol' => 'set', 'decimal_places' => 0],
        ];

        $units = [];
        foreach ($unitsData as $u) {
            $units[$u['code']] = Unit::firstOrCreate(
                ['code' => $u['code']],
                array_merge($u, ['status_id' => $activeStatusId])
            );
        }

        // 4. 50+ High-Quality Realistic Products
        $products = [
            // --- Beverages (1 to 10) ---
            [
                'sku' => 'BEV-003',
                'barcode' => '8850123456811',
                'name' => 'Pepsi Max Zero Sugar Can 330ml',
                'category_code' => 'CAT-BEV',
                'brand_code' => 'BR-PEPSI',
                'unit_code' => 'CAN',
                'cost_price' => 0.38,
                'selling_price' => 0.85,
                'wholesale_price' => 0.60,
                'vip_price' => 0.75,
                'member_price' => 0.80,
                'online_price' => 0.85,
                'opening_stock' => 180,
                'min_stock' => 24,
                'reorder_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Zero calorie crisp refreshing cola in sleek aluminum can',
                'description' => 'Pepsi Max delivers maximum cola taste with zero sugar and zero calories. Best served chilled.',
                'tags' => ['Beverage', 'Soda', 'Zero Sugar', 'Pepsi', 'Chilled'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'BEV-004',
                'barcode' => '8850123456812',
                'name' => 'Red Bull Energy Drink Classic 250ml',
                'category_code' => 'CAT-BEV',
                'brand_code' => 'BR-REDBULL',
                'unit_code' => 'CAN',
                'cost_price' => 0.95,
                'selling_price' => 1.85,
                'wholesale_price' => 1.40,
                'vip_price' => 1.65,
                'member_price' => 1.75,
                'online_price' => 1.85,
                'opening_stock' => 120,
                'min_stock' => 20,
                'reorder_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Vitalizes body and mind with taurine, B-vitamins, and caffeine',
                'description' => 'Red Bull Energy Drink is appreciated worldwide by top athletes, busy professionals, and college students.',
                'tags' => ['Energy Drink', 'Caffeine', 'Red Bull', 'Functional'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'BEV-005',
                'barcode' => '8850123456813',
                'name' => 'San Pellegrino Sparkling Mineral Water 500ml Glass Bottle',
                'category_code' => 'CAT-BEV',
                'brand_code' => 'BR-SANPELLEGRINO',
                'unit_code' => 'BTL',
                'cost_price' => 1.10,
                'selling_price' => 2.25,
                'wholesale_price' => 1.65,
                'vip_price' => 2.00,
                'member_price' => 2.10,
                'online_price' => 2.25,
                'opening_stock' => 90,
                'min_stock' => 15,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1560023907-5f339617ea30?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Italian natural mineral water with fine, elegant effervescence',
                'description' => 'Bottled at the natural spring in Val Brembana, Italy. Unmistakable gentle bubbles and mineral palate.',
                'tags' => ['Water', 'Sparkling', 'Italian', 'San Pellegrino', 'Fine Dining'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'BEV-006',
                'barcode' => '8850123456814',
                'name' => 'San Pellegrino Aranciata Rossa Blood Orange 330ml Can',
                'category_code' => 'CAT-BEV',
                'brand_code' => 'BR-SANPELLEGRINO',
                'unit_code' => 'CAN',
                'cost_price' => 1.05,
                'selling_price' => 2.10,
                'wholesale_price' => 1.55,
                'vip_price' => 1.90,
                'member_price' => 2.00,
                'online_price' => 2.10,
                'opening_stock' => 75,
                'min_stock' => 12,
                'reorder_level' => 18,
                'image_url' => 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Sparkling blood orange citrus beverage made with Mediterranean fruit juice',
                'description' => 'A dazzling blend of sparkling water and sun-ripened blood orange juice from Sicily.',
                'tags' => ['Beverage', 'Citrus', 'Blood Orange', 'Italian Soda'],
                'is_featured' => false,
                'is_new' => true,
            ],
            [
                'sku' => 'BEV-007',
                'barcode' => '8850123456815',
                'name' => 'Fanta Orange Sparkling Soda 330ml Can',
                'category_code' => 'CAT-BEV',
                'brand_code' => 'BR-COCA',
                'unit_code' => 'CAN',
                'cost_price' => 0.35,
                'selling_price' => 0.75,
                'wholesale_price' => 0.55,
                'vip_price' => 0.68,
                'member_price' => 0.70,
                'online_price' => 0.75,
                'opening_stock' => 160,
                'min_stock' => 24,
                'reorder_level' => 36,
                'image_url' => 'https://images.unsplash.com/photo-1624517452488-04869289c4ca?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Fruity vibrant orange soda bursting with effervescent citrus flavor',
                'description' => 'Bright, bubbly, instantly refreshing orange soda that brings fun to any gathering.',
                'tags' => ['Beverage', 'Fanta', 'Orange', 'Soda', 'Coca-Cola'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'BEV-008',
                'barcode' => '8850123456816',
                'name' => 'Sprite Lemon-Lime Soda 330ml Can',
                'category_code' => 'CAT-BEV',
                'brand_code' => 'BR-COCA',
                'unit_code' => 'CAN',
                'cost_price' => 0.35,
                'selling_price' => 0.75,
                'wholesale_price' => 0.55,
                'vip_price' => 0.68,
                'member_price' => 0.70,
                'online_price' => 0.75,
                'opening_stock' => 150,
                'min_stock' => 24,
                'reorder_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Crisp clean lemon-lime caffeine-free sparkling soda',
                'description' => 'Sprite delivers a clean, crisp lemon-lime taste that quenches thirst instantly.',
                'tags' => ['Beverage', 'Sprite', 'Lemon Lime', 'Soda'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'BEV-009',
                'barcode' => '8850123456901',
                'name' => 'Evian Natural Spring Mineral Water 750ml Sports Cap',
                'category_code' => 'CAT-BEV',
                'brand_code' => 'BR-SANPELLEGRINO',
                'unit_code' => 'BTL',
                'cost_price' => 1.15,
                'selling_price' => 2.40,
                'wholesale_price' => 1.70,
                'vip_price' => 2.10,
                'member_price' => 2.20,
                'online_price' => 2.40,
                'opening_stock' => 95,
                'min_stock' => 15,
                'reorder_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Pure alpine mineral water naturally filtered through French glacial rocks',
                'description' => 'Naturally balanced electrolytes with a signature crisp and refreshing taste.',
                'tags' => ['Water', 'Evian', 'Mineral Water', 'Hydration'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'BEV-010',
                'barcode' => '8850123456902',
                'name' => 'Monster Energy Original Green 500ml Mega Can',
                'category_code' => 'CAT-BEV',
                'brand_code' => 'BR-REDBULL',
                'unit_code' => 'CAN',
                'cost_price' => 1.30,
                'selling_price' => 2.65,
                'wholesale_price' => 1.95,
                'vip_price' => 2.35,
                'member_price' => 2.45,
                'online_price' => 2.65,
                'opening_stock' => 110,
                'min_stock' => 18,
                'reorder_level' => 24,
                'image_url' => 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Unleash the Beast! High energy blend with B-vitamins and ginseng',
                'description' => 'Smooth easy-drinking flavor that packs a powerful punch for athletes and gamers.',
                'tags' => ['Energy Drink', 'Monster Energy', 'Caffeine', 'Soda'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'BEV-011',
                'barcode' => '8850123456920',
                'name' => 'Coca-Cola Vanilla 330ml Can (Special Edition)',
                'category_code' => 'CAT-BEV',
                'brand_code' => 'BR-COCA',
                'unit_code' => 'CAN',
                'cost_price' => 0.48,
                'selling_price' => 0.99,
                'wholesale_price' => 0.72,
                'vip_price' => 0.88,
                'member_price' => 0.92,
                'online_price' => 0.99,
                'opening_stock' => 120,
                'min_stock' => 20,
                'reorder_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Classic Coca-Cola taste smoothly infused with rich French vanilla flavor',
                'description' => 'A sweet velvety twist on the worlds favorite cola beverage.',
                'tags' => ['Beverage', 'Coca-Cola', 'Vanilla', 'Soda'],
                'is_featured' => false,
                'is_new' => true,
            ],
            [
                'sku' => 'BEV-012',
                'barcode' => '8850123456921',
                'name' => 'Schweppes Indian Tonic Water with Quinine 330ml Can',
                'category_code' => 'CAT-BEV',
                'brand_code' => 'BR-SCHWEPPES',
                'unit_code' => 'CAN',
                'cost_price' => 0.42,
                'selling_price' => 0.95,
                'wholesale_price' => 0.68,
                'vip_price' => 0.85,
                'member_price' => 0.90,
                'online_price' => 0.95,
                'opening_stock' => 100,
                'min_stock' => 15,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Legendary sparkling tonic water crafted with quinine and citrus zest',
                'description' => 'The ultimate companion for mocktails and classic cocktails with signature crisp bitterness.',
                'tags' => ['Beverage', 'Tonic', 'Schweppes', 'Mixer'],
                'is_featured' => false,
                'is_new' => false,
            ],

            // --- Coffee & Tea (11 to 16) ---
            [
                'sku' => 'COF-001',
                'barcode' => '8850123456821',
                'name' => 'Starbucks Pike Place Roast Whole Bean Coffee 250g',
                'category_code' => 'CAT-COF',
                'brand_code' => 'BR-STARBUCKS',
                'unit_code' => 'PCK',
                'cost_price' => 5.20,
                'selling_price' => 9.50,
                'wholesale_price' => 7.20,
                'vip_price' => 8.50,
                'member_price' => 8.90,
                'online_price' => 9.50,
                'opening_stock' => 60,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Smooth medium roast with subtle notes of cocoa and toasted nuts',
                'description' => 'Named after the first Starbucks store in Seattles Pike Place Market. Well-rounded with subtle notes of cocoa.',
                'tags' => ['Coffee', 'Whole Bean', 'Starbucks', 'Medium Roast', 'Arabica'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'COF-002',
                'barcode' => '8850123456822',
                'name' => 'Starbucks Espresso Roast Dark Beans 250g',
                'category_code' => 'CAT-COF',
                'brand_code' => 'BR-STARBUCKS',
                'unit_code' => 'PCK',
                'cost_price' => 5.40,
                'selling_price' => 9.80,
                'wholesale_price' => 7.50,
                'vip_price' => 8.80,
                'member_price' => 9.20,
                'online_price' => 9.80,
                'opening_stock' => 55,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Intense caramelly dark roast with rich full-bodied crema',
                'description' => 'The cornerstone of all Starbucks handcrafted espresso beverages. Rich with molasses and caramelized sugar notes.',
                'tags' => ['Coffee', 'Dark Roast', 'Espresso', 'Starbucks'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'COF-003',
                'barcode' => '8850123456823',
                'name' => 'Nescafe Gold Rich and Smooth Instant Coffee Glass Jar 200g',
                'category_code' => 'CAT-COF',
                'brand_code' => 'BR-NESTLE',
                'unit_code' => 'BTL',
                'cost_price' => 4.10,
                'selling_price' => 7.80,
                'wholesale_price' => 5.90,
                'vip_price' => 6.90,
                'member_price' => 7.20,
                'online_price' => 7.80,
                'opening_stock' => 70,
                'min_stock' => 12,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1587080413959-06b859fb107d?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Golden roasted premium arabica and robusta soluble instant coffee',
                'description' => 'Carefully roasted mountain-grown beans unlocked into a rich and silky aroma with velvety smooth finish.',
                'tags' => ['Coffee', 'Instant Coffee', 'Nescafe', 'Nestle', 'Gold'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'COF-004',
                'barcode' => '8850123456824',
                'name' => 'Nescafe Dolce Gusto Caramel Latte Macchiato 16 Pods Box',
                'category_code' => 'CAT-COF',
                'brand_code' => 'BR-NESTLE',
                'unit_code' => 'BOX',
                'cost_price' => 6.20,
                'selling_price' => 11.50,
                'wholesale_price' => 8.80,
                'vip_price' => 10.20,
                'member_price' => 10.80,
                'online_price' => 11.50,
                'opening_stock' => 40,
                'min_stock' => 8,
                'reorder_level' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Decadent layered caramel latte macchiato capsule pods',
                'description' => 'Layered steamed whole milk froth, smooth aromatic espresso, and delicious caramel sweetness.',
                'tags' => ['Coffee Pods', 'Dolce Gusto', 'Caramel Latte', 'Capsules'],
                'is_featured' => false,
                'is_new' => true,
            ],
            [
                'sku' => 'COF-005',
                'barcode' => '8850123456825',
                'name' => 'Organic Japanese Ceremonial Grade Matcha Powder 100g Tin',
                'category_code' => 'CAT-COF',
                'brand_code' => 'BR-STARBUCKS',
                'unit_code' => 'PCK',
                'cost_price' => 9.50,
                'selling_price' => 18.00,
                'wholesale_price' => 13.50,
                'vip_price' => 16.00,
                'member_price' => 16.80,
                'online_price' => 18.00,
                'opening_stock' => 35,
                'min_stock' => 6,
                'reorder_level' => 10,
                'image_url' => 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&auto=format&fit=crop&q=80',
                'short_description' => '100% pure stone-ground vibrant green ceremonial matcha from Uji, Kyoto',
                'description' => 'Rich in L-theanine and antioxidants. Yields vibrant emerald tea with sweet umami aroma and zero bitterness.',
                'tags' => ['Tea', 'Matcha', 'Ceremonial', 'Organic', 'Japanese Green Tea'],
                'is_featured' => true,
                'is_new' => true,
            ],
            [
                'sku' => 'COF-006',
                'barcode' => '8850123456826',
                'name' => 'Twinings Traditional English Breakfast Tea 50 Foil Bags Box',
                'category_code' => 'CAT-COF',
                'brand_code' => 'BR-TWININGS',
                'unit_code' => 'BOX',
                'cost_price' => 2.90,
                'selling_price' => 5.75,
                'wholesale_price' => 4.20,
                'vip_price' => 4.95,
                'member_price' => 5.20,
                'online_price' => 5.75,
                'opening_stock' => 70,
                'min_stock' => 12,
                'reorder_level' => 18,
                'image_url' => 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Golden full-bodied black tea expertly blended from Kenyan and Assam tea leaves',
                'description' => 'A hearty and invigorating classic morning brew that goes wonderfully with a splash of cold fresh milk.',
                'tags' => ['Tea', 'Black Tea', 'English Breakfast', 'Twinings', 'Hot Beverage'],
                'is_featured' => false,
                'is_new' => false,
            ],

            // --- Snacks & Confectionery (17 to 24) ---
            [
                'sku' => 'SNK-002',
                'barcode' => '8850123456831',
                'name' => 'Lays Sour Cream and Onion Potato Chips 170g Party Size',
                'category_code' => 'CAT-SNK',
                'brand_code' => 'BR-LAYS',
                'unit_code' => 'PCK',
                'cost_price' => 1.20,
                'selling_price' => 2.45,
                'wholesale_price' => 1.80,
                'vip_price' => 2.15,
                'member_price' => 2.25,
                'online_price' => 2.45,
                'opening_stock' => 85,
                'min_stock' => 15,
                'reorder_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Crispy golden sliced potatoes seasoned with savoury sour cream and herbs',
                'description' => 'Iconic crunchy potato chips with rich tangy sour cream and savoury garden herbs.',
                'tags' => ['Snacks', 'Chips', 'Lays', 'Sour Cream', 'Party Size'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'SNK-003',
                'barcode' => '8850123456832',
                'name' => 'Lays Barbecue Flavour Potato Crisps 170g',
                'category_code' => 'CAT-SNK',
                'brand_code' => 'BR-LAYS',
                'unit_code' => 'PCK',
                'cost_price' => 1.20,
                'selling_price' => 2.45,
                'wholesale_price' => 1.80,
                'vip_price' => 2.15,
                'member_price' => 2.25,
                'online_price' => 2.45,
                'opening_stock' => 80,
                'min_stock' => 15,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Smoky sweet barbecue flavoured crunchy golden potato chips',
                'description' => 'Infused with hickory smoke, brown sugar and sweet aromatic spices for barbecue lovers.',
                'tags' => ['Snacks', 'Chips', 'Lays', 'BBQ'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'SNK-004',
                'barcode' => '8850123456833',
                'name' => 'Lindt Lindor Assorted Swiss Chocolate Truffles Box 200g',
                'category_code' => 'CAT-SNK',
                'brand_code' => 'BR-LINDT',
                'unit_code' => 'BOX',
                'cost_price' => 4.80,
                'selling_price' => 8.95,
                'wholesale_price' => 6.80,
                'vip_price' => 7.95,
                'member_price' => 8.30,
                'online_price' => 8.95,
                'opening_stock' => 65,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Irresistibly smooth melting chocolate centres in milk, dark, and hazelnut',
                'description' => 'Master Swiss Chocolatier selection featuring delicate chocolate shells with smooth melting centers.',
                'tags' => ['Chocolate', 'Lindt', 'Swiss Chocolate', 'Truffles', 'Gift'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'SNK-005',
                'barcode' => '8850123456834',
                'name' => 'Lindt Excellence 85 Percent Cocoa Extra Dark Chocolate Bar 100g',
                'category_code' => 'CAT-SNK',
                'brand_code' => 'BR-LINDT',
                'unit_code' => 'PCK',
                'cost_price' => 2.10,
                'selling_price' => 3.99,
                'wholesale_price' => 2.95,
                'vip_price' => 3.50,
                'member_price' => 3.70,
                'online_price' => 3.99,
                'opening_stock' => 90,
                'min_stock' => 15,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1548907040-4baa42d10919?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Full-bodied extra dark chocolate with notes of roasted coffee and dried fruit',
                'description' => 'An intensely satisfying dark chocolate bar crafted by Lindt master chocolatiers with 85% pure cocoa solids.',
                'tags' => ['Dark Chocolate', 'Lindt', '85% Cocoa', 'Gourmet'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'SNK-006',
                'barcode' => '8850123456835',
                'name' => 'KitKat 4-Finger Milk Chocolate Crisp Wafer Bar 41.5g',
                'category_code' => 'CAT-SNK',
                'brand_code' => 'BR-NESTLE',
                'unit_code' => 'PCS',
                'cost_price' => 0.45,
                'selling_price' => 0.99,
                'wholesale_price' => 0.70,
                'vip_price' => 0.85,
                'member_price' => 0.90,
                'online_price' => 0.99,
                'opening_stock' => 220,
                'min_stock' => 30,
                'reorder_level' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Crispy wafer fingers covered in smooth milk chocolate. Have a break, have a KitKat',
                'description' => 'The perfect balance of crisp wafer and smooth milk chocolate for a quick snack break.',
                'tags' => ['Chocolate', 'KitKat', 'Wafer', 'Nestle', 'Snack'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'SNK-007',
                'barcode' => '8850123456836',
                'name' => 'Oreo Double Stuf Sandwich Cookies Family Pack 432g',
                'category_code' => 'CAT-SNK',
                'brand_code' => 'BR-NESTLE',
                'unit_code' => 'PCK',
                'cost_price' => 1.95,
                'selling_price' => 3.75,
                'wholesale_price' => 2.80,
                'vip_price' => 3.30,
                'member_price' => 3.50,
                'online_price' => 3.75,
                'opening_stock' => 80,
                'min_stock' => 12,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Double vanilla creme filled rich chocolate sandwich biscuits',
                'description' => 'Twist, lick, and dunk! Double the smooth sweet creme between two rich chocolate cookies.',
                'tags' => ['Cookies', 'Oreo', 'Biscuits', 'Snacks'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'SNK-008',
                'barcode' => '8850123456903',
                'name' => 'Pringles Original Salted Potato Crisps 165g Canister',
                'category_code' => 'CAT-SNK',
                'brand_code' => 'BR-LAYS',
                'unit_code' => 'CAN',
                'cost_price' => 1.40,
                'selling_price' => 2.85,
                'wholesale_price' => 2.05,
                'vip_price' => 2.50,
                'member_price' => 2.65,
                'online_price' => 2.85,
                'opening_stock' => 85,
                'min_stock' => 15,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Iconic hyperboloid saddle crisps in resealable stay-fresh cylindrical canister',
                'description' => 'Once you pop, the fun dont stop! Perfectly salted crisp potato snack.',
                'tags' => ['Chips', 'Pringles', 'Snacks', 'Crisps'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'SNK-010',
                'barcode' => '8850123456905',
                'name' => 'Snickers Single Milk Chocolate Peanut Caramel Bar 50g',
                'category_code' => 'CAT-SNK',
                'brand_code' => 'BR-NESTLE',
                'unit_code' => 'PCS',
                'cost_price' => 0.50,
                'selling_price' => 1.10,
                'wholesale_price' => 0.78,
                'vip_price' => 0.95,
                'member_price' => 1.00,
                'online_price' => 1.10,
                'opening_stock' => 180,
                'min_stock' => 25,
                'reorder_level' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1582293041079-7814c2f12063?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Roasted peanuts, nougat, caramel, and milk chocolate bar',
                'description' => 'You are not you when you are hungry! Satisfies deep cravings on the go.',
                'tags' => ['Chocolate', 'Snickers', 'Peanuts', 'Caramel', 'Candy'],
                'is_featured' => false,
                'is_new' => false,
            ],

            // --- Pantry & Grocery Essentials (25 to 32) ---
            [
                'sku' => 'GRO-001',
                'barcode' => '8850123456841',
                'name' => 'Barilla Spaghetti No. 5 Durum Wheat Pasta 500g',
                'category_code' => 'CAT-GRO',
                'brand_code' => 'BR-BARILLA',
                'unit_code' => 'PCK',
                'cost_price' => 0.95,
                'selling_price' => 1.95,
                'wholesale_price' => 1.45,
                'vip_price' => 1.75,
                'member_price' => 1.85,
                'online_price' => 1.95,
                'opening_stock' => 110,
                'min_stock' => 20,
                'reorder_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1621996346565-e3d5d6281699?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Authentic Italian spaghetti made from 100% selected durum wheat semolina',
                'description' => 'Cooks to al dente perfection in 8 minutes. Pairs brilliantly with bolognese, carbonara, and aglio e olio.',
                'tags' => ['Pasta', 'Spaghetti', 'Barilla', 'Italian', 'Pantry'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'GRO-002',
                'barcode' => '8850123456842',
                'name' => 'Barilla Penne Rigate No. 73 Pasta 500g',
                'category_code' => 'CAT-GRO',
                'brand_code' => 'BR-BARILLA',
                'unit_code' => 'PCK',
                'cost_price' => 0.95,
                'selling_price' => 1.95,
                'wholesale_price' => 1.45,
                'vip_price' => 1.75,
                'member_price' => 1.85,
                'online_price' => 1.95,
                'opening_stock' => 100,
                'min_stock' => 15,
                'reorder_level' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Ridged cylinder pasta that holds rich tomato and cream sauces effortlessly',
                'description' => 'High quality Italian semolina pasta with deep ridges designed to capture every drop of savory sauce.',
                'tags' => ['Pasta', 'Penne', 'Barilla', 'Italian'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'GRO-003',
                'barcode' => '8850123456843',
                'name' => 'Barilla Basilico Italian Tomato and Basil Pasta Sauce 400g Glass Jar',
                'category_code' => 'CAT-GRO',
                'brand_code' => 'BR-BARILLA',
                'unit_code' => 'BTL',
                'cost_price' => 1.85,
                'selling_price' => 3.50,
                'wholesale_price' => 2.65,
                'vip_price' => 3.10,
                'member_price' => 3.25,
                'online_price' => 3.50,
                'opening_stock' => 85,
                'min_stock' => 12,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Slow-cooked Italian sun-ripened tomatoes and freshly chopped fragrant basil',
                'description' => 'No added preservatives, naturally gluten-free sauce ready to warm and toss directly onto freshly boiled pasta.',
                'tags' => ['Sauce', 'Tomato Sauce', 'Basilico', 'Barilla', 'Italian'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'GRO-004',
                'barcode' => '8850123456844',
                'name' => 'Barilla Genovese Classic Basil Pesto Sauce 190g Glass Jar',
                'category_code' => 'CAT-GRO',
                'brand_code' => 'BR-BARILLA',
                'unit_code' => 'BTL',
                'cost_price' => 2.40,
                'selling_price' => 4.60,
                'wholesale_price' => 3.50,
                'vip_price' => 4.10,
                'member_price' => 4.30,
                'online_price' => 4.60,
                'opening_stock' => 60,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Creamy basil pesto made with fragrant Italian basil and Parmigiano Reggiano',
                'description' => 'Authentic pesto alla Genovese bursting with freshly harvested basil, extra virgin olive oil, and aged parmesan cheese.',
                'tags' => ['Pesto', 'Barilla', 'Italian', 'Gourmet Sauce'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'GRO-005',
                'barcode' => '8850123456845',
                'name' => 'Nestle Carnation Sweetened Condensed Milk 388g Can',
                'category_code' => 'CAT-GRO',
                'brand_code' => 'BR-NESTLE',
                'unit_code' => 'CAN',
                'cost_price' => 0.85,
                'selling_price' => 1.65,
                'wholesale_price' => 1.25,
                'vip_price' => 1.45,
                'member_price' => 1.55,
                'online_price' => 1.65,
                'opening_stock' => 140,
                'min_stock' => 20,
                'reorder_level' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Rich sweet creamy condensed milk ideal for iced coffee, tea, and baking',
                'description' => 'The essential ingredient for Southeast Asian iced coffee, flan, banoffee pie, and delicious sweet desserts.',
                'tags' => ['Dairy', 'Condensed Milk', 'Nestle', 'Baking', 'Coffee'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'GRO-006',
                'barcode' => '8850123456906',
                'name' => 'Filippo Berio Extra Virgin Olive Oil 500ml Glass Bottle',
                'category_code' => 'CAT-GRO',
                'brand_code' => 'BR-BARILLA',
                'unit_code' => 'BTL',
                'cost_price' => 5.50,
                'selling_price' => 9.90,
                'wholesale_price' => 7.50,
                'vip_price' => 8.80,
                'member_price' => 9.20,
                'online_price' => 9.90,
                'opening_stock' => 55,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'First cold pressed extra virgin olive oil with rich fruity aroma',
                'description' => 'Perfect for drizzling over fresh salads, dipping crusty artisan bread, and roasting vegetables.',
                'tags' => ['Olive Oil', 'Extra Virgin', 'Gourmet', 'Italian Cooking'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'GRO-007',
                'barcode' => '8850123456907',
                'name' => 'Nutella Hazelnut Spread with Cocoa Glass Jar 350g',
                'category_code' => 'CAT-GRO',
                'brand_code' => 'BR-NESTLE',
                'unit_code' => 'BTL',
                'cost_price' => 2.40,
                'selling_price' => 4.60,
                'wholesale_price' => 3.40,
                'vip_price' => 4.10,
                'member_price' => 4.30,
                'online_price' => 4.60,
                'opening_stock' => 75,
                'min_stock' => 12,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Creamy cocoa and roasted hazelnut breakfast spread',
                'description' => 'Spread on warm toast, pancakes, waffles, or fresh fruit for a delicious morning treat.',
                'tags' => ['Nutella', 'Hazelnut Spread', 'Chocolate', 'Breakfast'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'GRO-008',
                'barcode' => '8850123456908',
                'name' => 'Quaker Whole Grain Rolled Oats 800g Tub',
                'category_code' => 'CAT-GRO',
                'brand_code' => 'BR-PEPSI',
                'unit_code' => 'PCK',
                'cost_price' => 2.10,
                'selling_price' => 4.20,
                'wholesale_price' => 3.10,
                'vip_price' => 3.70,
                'member_price' => 3.90,
                'online_price' => 4.20,
                'opening_stock' => 60,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&auto=format&fit=crop&q=80',
                'short_description' => '100% natural whole grain rolled oats high in beta-glucan soluble fiber',
                'description' => 'Heart-healthy breakfast staple ideal for warm porridge, overnight oats, baking cookies, and smoothies.',
                'tags' => ['Oats', 'Breakfast', 'Healthy', 'Fiber', 'Quaker'],
                'is_featured' => false,
                'is_new' => false,
            ],

            // --- Consumer Electronics & Accessories (33 to 40) ---
            [
                'sku' => 'ELE-001',
                'barcode' => '8850123456851',
                'name' => 'Apple 20W USB-C Power Adapter Fast Charger',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-APPLE',
                'unit_code' => 'PCS',
                'cost_price' => 12.50,
                'selling_price' => 22.00,
                'wholesale_price' => 17.00,
                'vip_price' => 19.50,
                'member_price' => 20.50,
                'online_price' => 22.00,
                'opening_stock' => 45,
                'min_stock' => 8,
                'reorder_level' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Official compact 20-watt USB-C wall adapter for iPhone and iPad fast charging',
                'description' => 'Charges iPhone from 0 to 50% in approximately 30 minutes. Features built-in surge and overheating protection.',
                'tags' => ['Electronics', 'Apple', 'Charger', 'USB-C', 'Fast Charging'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'ELE-002',
                'barcode' => '8850123456852',
                'name' => 'Apple USB-C to USB-C Woven Braided Cable (1m / 60W)',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-APPLE',
                'unit_code' => 'PCS',
                'cost_price' => 9.80,
                'selling_price' => 19.00,
                'wholesale_price' => 14.50,
                'vip_price' => 17.00,
                'member_price' => 18.00,
                'online_price' => 19.00,
                'opening_stock' => 50,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Durable woven white cable supporting fast charging and high-speed data transfer',
                'description' => 'Tangle-resistant braided exterior designed for iPhone 15/16 series, iPads, and MacBooks up to 60W power delivery.',
                'tags' => ['Electronics', 'Apple', 'Cable', 'USB-C', 'Braided'],
                'is_featured' => false,
                'is_new' => true,
            ],
            [
                'sku' => 'ELE-003',
                'barcode' => '8850123456853',
                'name' => 'Samsung 25W Super Fast Charging Wall Adapter (Type-C)',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-SAMSUNG',
                'unit_code' => 'PCS',
                'cost_price' => 10.20,
                'selling_price' => 19.50,
                'wholesale_price' => 15.00,
                'vip_price' => 17.50,
                'member_price' => 18.50,
                'online_price' => 19.50,
                'opening_stock' => 40,
                'min_stock' => 8,
                'reorder_level' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'PD 3.0 PPS 25-watt power delivery charger for Galaxy phones and tablets',
                'description' => 'Powers Galaxy S24, S23, and Galaxy Tab with optimized PPS adaptive high-efficiency fast charging.',
                'tags' => ['Electronics', 'Samsung', 'Charger', '25W', 'PPS'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'ELE-004',
                'barcode' => '8850123456854',
                'name' => 'Sony WH-1000XM5 Wireless Active Noise Cancelling Headphones',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-SONY',
                'unit_code' => 'PCS',
                'cost_price' => 240.00,
                'selling_price' => 379.00,
                'wholesale_price' => 310.00,
                'vip_price' => 345.00,
                'member_price' => 355.00,
                'online_price' => 379.00,
                'opening_stock' => 15,
                'min_stock' => 3,
                'reorder_level' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Industry-leading noise cancellation with 8 microphones and 30-hour battery life',
                'description' => 'Integrated Processor V1 and QN1 chip deliver flawless studio-quality audio, crystal-clear calls, and multipoint Bluetooth.',
                'tags' => ['Electronics', 'Audio', 'Headphones', 'Sony', 'ANC', 'Bluetooth'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'ELE-005',
                'barcode' => '8850123456855',
                'name' => 'Sony WF-1000XM5 True Wireless Noise Cancelling Earbuds',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-SONY',
                'unit_code' => 'PCS',
                'cost_price' => 170.00,
                'selling_price' => 269.00,
                'wholesale_price' => 215.00,
                'vip_price' => 245.00,
                'member_price' => 255.00,
                'online_price' => 269.00,
                'opening_stock' => 20,
                'min_stock' => 4,
                'reorder_level' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Astonishing sound quality and cutting edge noise cancellation in compact earbuds',
                'description' => 'High-resolution wireless audio with LDAC, AI-based noise reduction for calls, IPX4 water resistance, and wireless charging case.',
                'tags' => ['Electronics', 'Earbuds', 'Sony', 'Wireless', 'ANC'],
                'is_featured' => true,
                'is_new' => true,
            ],
            [
                'sku' => 'ELE-006',
                'barcode' => '8850123456856',
                'name' => 'Anker 737 Power Bank (PowerCore 24K, 140W Output, Smart Display)',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-ANKER',
                'unit_code' => 'PCS',
                'cost_price' => 78.00,
                'selling_price' => 129.99,
                'wholesale_price' => 98.00,
                'vip_price' => 115.00,
                'member_price' => 120.00,
                'online_price' => 129.99,
                'opening_stock' => 28,
                'min_stock' => 5,
                'reorder_level' => 8,
                'image_url' => 'https://images.unsplash.com/photo-1609592424300-333333333333?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Ultra-powerful 24,000mAh portable charger with 140W two-way fast charging',
                'description' => 'Can charge a 16-inch MacBook Pro or fast charge 3 devices at once. Includes real-time color digital smart display.',
                'tags' => ['Electronics', 'Anker', 'Power Bank', '140W', 'Laptop Charger'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'ELE-007',
                'barcode' => '8850123456857',
                'name' => 'Logitech MX Master 3S Wireless Performance Mouse (Graphite)',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-LOGITECH',
                'unit_code' => 'PCS',
                'cost_price' => 62.00,
                'selling_price' => 99.00,
                'wholesale_price' => 78.00,
                'vip_price' => 89.00,
                'member_price' => 93.00,
                'online_price' => 99.00,
                'opening_stock' => 35,
                'min_stock' => 6,
                'reorder_level' => 10,
                'image_url' => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Ergonomic wireless mouse with Quiet Clicks and 8K DPI glass sensor',
                'description' => 'MagSpeed electromagnetic scroll wheel scrolls 1,000 lines per second. Seamless control across up to 3 computers.',
                'tags' => ['Electronics', 'Mouse', 'Logitech', 'MX Master', 'Ergonomic', 'Productivity'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'ELE-008',
                'barcode' => '8850123456858',
                'name' => 'Logitech MX Keys S Advanced Wireless Illuminated Keyboard',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-LOGITECH',
                'unit_code' => 'PCS',
                'cost_price' => 68.00,
                'selling_price' => 109.00,
                'wholesale_price' => 85.00,
                'vip_price' => 98.00,
                'member_price' => 102.00,
                'online_price' => 109.00,
                'opening_stock' => 30,
                'min_stock' => 5,
                'reorder_level' => 8,
                'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Fluid precision typing with spherically dished keys and smart backlighting',
                'description' => 'Crafted for stability and precision. Smart sensors illuminate keys when your hands approach.',
                'tags' => ['Electronics', 'Keyboard', 'Logitech', 'Wireless', 'Bluetooth'],
                'is_featured' => false,
                'is_new' => true,
            ],
            [
                'sku' => 'ELE-009',
                'barcode' => '8850123456909',
                'name' => 'Anker MagGo Magnetic Wireless Power Bank (Qi2 15W / 6600mAh)',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-ANKER',
                'unit_code' => 'PCS',
                'cost_price' => 38.00,
                'selling_price' => 69.99,
                'wholesale_price' => 52.00,
                'vip_price' => 61.00,
                'member_price' => 65.00,
                'online_price' => 69.99,
                'opening_stock' => 35,
                'min_stock' => 6,
                'reorder_level' => 10,
                'image_url' => 'https://images.unsplash.com/photo-1609592424300-333333333333?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Ultra-fast 15W certified Qi2 magnetic wireless charger with foldable kickstand',
                'description' => 'Snaps seamlessly to iPhone 15/14/13/12 models. Built-in adjustable phone stand for hands-free video viewing.',
                'tags' => ['Electronics', 'Anker', 'MagSafe', 'Power Bank', 'Wireless Charging'],
                'is_featured' => true,
                'is_new' => true,
            ],
            [
                'sku' => 'ELE-010',
                'barcode' => '8850123456910',
                'name' => 'Samsung Galaxy Buds2 Pro Wireless Earbuds (Graphite)',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-SAMSUNG',
                'unit_code' => 'PCS',
                'cost_price' => 110.00,
                'selling_price' => 189.00,
                'wholesale_price' => 145.00,
                'vip_price' => 169.00,
                'member_price' => 175.00,
                'online_price' => 189.00,
                'opening_stock' => 25,
                'min_stock' => 5,
                'reorder_level' => 8,
                'image_url' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
                'short_description' => '24-bit Hi-Fi audio with intelligent 360 Audio and enhanced Active Noise Cancellation',
                'description' => 'Ergonomically designed for secure comfort. IPX7 water resistance and seamless automatic switching across Galaxy devices.',
                'tags' => ['Electronics', 'Samsung', 'Earbuds', 'Hi-Fi', 'ANC'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'ELE-011',
                'barcode' => '8850123456911',
                'name' => 'Apple Magic Mouse Multi-Touch Wireless (Black)',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-APPLE',
                'unit_code' => 'PCS',
                'cost_price' => 58.00,
                'selling_price' => 95.00,
                'wholesale_price' => 74.00,
                'vip_price' => 85.00,
                'member_price' => 89.00,
                'online_price' => 95.00,
                'opening_stock' => 20,
                'min_stock' => 4,
                'reorder_level' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Rechargeable wireless multi-touch surface mouse for Mac and iPad',
                'description' => 'Allows intuitive gestures such as swiping between web pages and scrolling through documents with smooth glass glide.',
                'tags' => ['Electronics', 'Apple', 'Magic Mouse', 'Mac', 'Bluetooth'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'ELE-012',
                'barcode' => '8850123456912',
                'name' => 'Apple AirTag Bluetooth Item Tracker 1-Pack',
                'category_code' => 'CAT-ELE',
                'brand_code' => 'BR-APPLE',
                'unit_code' => 'PCS',
                'cost_price' => 19.50,
                'selling_price' => 32.00,
                'wholesale_price' => 24.50,
                'vip_price' => 28.50,
                'member_price' => 29.90,
                'online_price' => 32.00,
                'opening_stock' => 65,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Keep track of keys, wallet, luggage, and backpack via Apple Find My network',
                'description' => 'One-tap setup connects immediately to your iPhone or iPad. Built-in speaker plays sounds to help pinpoint items.',
                'tags' => ['Electronics', 'Apple', 'AirTag', 'Tracker', 'Find My'],
                'is_featured' => true,
                'is_new' => false,
            ],

            // --- Personal Care & Health (41 to 46) ---
            [
                'sku' => 'HEA-001',
                'barcode' => '8850123456861',
                'name' => 'LOreal Paris Revitalift Hyaluronic Acid 1.5 Percent Hydrating Serum 30ml',
                'category_code' => 'CAT-HEA',
                'brand_code' => 'BR-LOREAL',
                'unit_code' => 'BTL',
                'cost_price' => 12.00,
                'selling_price' => 23.50,
                'wholesale_price' => 16.50,
                'vip_price' => 20.00,
                'member_price' => 21.50,
                'online_price' => 23.50,
                'opening_stock' => 50,
                'min_stock' => 8,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Pure hyaluronic acid anti-aging face serum for intense hydration and plump skin',
                'description' => 'Dermatologist-validated lightweight formula absorbs instantly without greasy residue. Visibly reduces fine wrinkles.',
                'tags' => ['Beauty', 'Skincare', 'Serum', 'LOreal', 'Hyaluronic Acid'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'HEA-002',
                'barcode' => '8850123456862',
                'name' => 'Nivea Rich Nourishing Body Lotion 48h Deep Moisture 400ml Pump',
                'category_code' => 'CAT-HEA',
                'brand_code' => 'BR-NIVEA',
                'unit_code' => 'BTL',
                'cost_price' => 3.20,
                'selling_price' => 6.50,
                'wholesale_price' => 4.80,
                'vip_price' => 5.60,
                'member_price' => 5.90,
                'online_price' => 6.50,
                'opening_stock' => 75,
                'min_stock' => 12,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Enriched with almond oil and deep moisture serum for dry to very dry skin',
                'description' => 'Provides continuous 48-hour moisture barrier protection while soothing and smoothing dry skin.',
                'tags' => ['Skincare', 'Body Lotion', 'Nivea', 'Moisturizer'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'HEA-003',
                'barcode' => '8850123456863',
                'name' => 'Nivea Men Deep Clean Shower Gel and Face Wash 500ml',
                'category_code' => 'CAT-HEA',
                'brand_code' => 'BR-NIVEA',
                'unit_code' => 'BTL',
                'cost_price' => 2.80,
                'selling_price' => 5.80,
                'wholesale_price' => 4.20,
                'vip_price' => 5.00,
                'member_price' => 5.30,
                'online_price' => 5.80,
                'opening_stock' => 60,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Micro-fine naturally derived active clay formula deeply absorbs dirt and oil',
                'description' => 'Refreshes body, face, and hair with masculine woody amber scent without drying the skin.',
                'tags' => ['Grooming', 'Men Care', 'Shower Gel', 'Nivea'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'HEA-004',
                'barcode' => '8850123456864',
                'name' => 'LOreal Men Expert Hydra Energetic Anti-Fatigue Moisturiser 50ml',
                'category_code' => 'CAT-HEA',
                'brand_code' => 'BR-LOREAL',
                'unit_code' => 'BTL',
                'cost_price' => 6.50,
                'selling_price' => 12.90,
                'wholesale_price' => 9.20,
                'vip_price' => 11.00,
                'member_price' => 11.80,
                'online_price' => 12.90,
                'opening_stock' => 45,
                'min_stock' => 8,
                'reorder_level' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1608248597359-53e7f9342738?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Vitamin C and Guarana infused energizing daily face cream fighting 5 signs of fatigue',
                'description' => 'Battles dullness, dark circles, tightness, loss of firmness, and roughness for 24 hours.',
                'tags' => ['Grooming', 'Face Cream', 'LOreal', 'Men Expert'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'HEA-005',
                'barcode' => '8850123456913',
                'name' => 'LOreal Paris Elvive Total Repair 5 Restoring Shampoo 400ml',
                'category_code' => 'CAT-HEA',
                'brand_code' => 'BR-LOREAL',
                'unit_code' => 'BTL',
                'cost_price' => 2.80,
                'selling_price' => 5.95,
                'wholesale_price' => 4.20,
                'vip_price' => 5.10,
                'member_price' => 5.40,
                'online_price' => 5.95,
                'opening_stock' => 80,
                'min_stock' => 12,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Keratin and ceramide infused shampoo restoring damaged hair fiber',
                'description' => 'Repairs 5 signs of damaged hair: split ends, dryness, roughness, dullness, and breakage.',
                'tags' => ['Haircare', 'Shampoo', 'LOreal', 'Total Repair'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'HEA-006',
                'barcode' => '8850123456914',
                'name' => 'Nivea Sun Protect and Moisture SPF50+ Sunscreen Lotion 200ml',
                'category_code' => 'CAT-HEA',
                'brand_code' => 'BR-NIVEA',
                'unit_code' => 'BTL',
                'cost_price' => 6.20,
                'selling_price' => 12.50,
                'wholesale_price' => 8.90,
                'vip_price' => 10.80,
                'member_price' => 11.40,
                'online_price' => 12.50,
                'opening_stock' => 50,
                'min_stock' => 8,
                'reorder_level' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Broad spectrum UVA and UVB water-resistant high protection sun lotion',
                'description' => 'Immediate skin barrier defense against sunburn and premature aging with deep 48h moisture.',
                'tags' => ['Sunscreen', 'SPF50', 'Nivea', 'Skincare', 'Sun Protection'],
                'is_featured' => true,
                'is_new' => false,
            ],

            // --- Home & Kitchen (47 to 51) ---
            [
                'sku' => 'HOM-001',
                'barcode' => '8850123456871',
                'name' => 'Philips Essential Airfryer XL 4.1L Rapid Air Technology',
                'category_code' => 'CAT-HOM',
                'brand_code' => 'BR-PHILIPS',
                'unit_code' => 'PCS',
                'cost_price' => 58.00,
                'selling_price' => 99.00,
                'wholesale_price' => 76.00,
                'vip_price' => 88.00,
                'member_price' => 92.00,
                'online_price' => 99.00,
                'opening_stock' => 25,
                'min_stock' => 4,
                'reorder_level' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Crispy delicious fried food with up to 90% less fat using Rapid Air technology',
                'description' => 'Touch screen with 7 presets, keep warm function, dishwasher safe removable basket, and recipe app integration.',
                'tags' => ['Home', 'Kitchen', 'Airfryer', 'Philips', 'Appliance'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'HOM-002',
                'barcode' => '8850123456872',
                'name' => 'Philips 3000 Series Handheld Garment Clothes Steamer 1000W',
                'category_code' => 'CAT-HOM',
                'brand_code' => 'BR-PHILIPS',
                'unit_code' => 'PCS',
                'cost_price' => 24.00,
                'selling_price' => 42.00,
                'wholesale_price' => 32.00,
                'vip_price' => 37.00,
                'member_price' => 39.00,
                'online_price' => 42.00,
                'opening_stock' => 30,
                'min_stock' => 5,
                'reorder_level' => 8,
                'image_url' => 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Compact foldable travel steamer kills 99.9% bacteria and removes wrinkles fast',
                'description' => 'Ready to steam in 30 seconds. Safe to use on all ironable fabrics with no burns guaranteed.',
                'tags' => ['Home', 'Appliance', 'Steamer', 'Philips', 'Travel'],
                'is_featured' => false,
                'is_new' => true,
            ],
            [
                'sku' => 'HOM-003',
                'barcode' => '8850123456873',
                'name' => 'Philips Sonicare ProtectiveClean 4300 Electric Toothbrush',
                'category_code' => 'CAT-HOM',
                'brand_code' => 'BR-PHILIPS',
                'unit_code' => 'PCS',
                'cost_price' => 38.00,
                'selling_price' => 69.00,
                'wholesale_price' => 52.00,
                'vip_price' => 61.00,
                'member_price' => 64.00,
                'online_price' => 69.00,
                'opening_stock' => 25,
                'min_stock' => 4,
                'reorder_level' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1559825481-12a05cc00344?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Removes up to 7x more plaque than manual toothbrushes with pressure sensor',
                'description' => 'Advanced sonic technology pulses water between teeth while 62,000 brush movements per minute gently polish.',
                'tags' => ['Health', 'Dental', 'Electric Toothbrush', 'Philips Sonicare'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'HOM-004',
                'barcode' => '8850123456915',
                'name' => 'Philips Daily Collection Electric Kettle 1.7L Stainless Steel',
                'category_code' => 'CAT-HOM',
                'brand_code' => 'BR-PHILIPS',
                'unit_code' => 'PCS',
                'cost_price' => 18.50,
                'selling_price' => 34.00,
                'wholesale_price' => 25.00,
                'vip_price' => 29.50,
                'member_price' => 31.00,
                'online_price' => 34.00,
                'opening_stock' => 30,
                'min_stock' => 5,
                'reorder_level' => 8,
                'image_url' => 'https://images.unsplash.com/photo-1594213114663-ddbe3f2a8335?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Fast boiling 2200W food-grade brushed stainless steel electric kettle',
                'description' => 'Spring lid with large opening for effortless cleaning, pilot light indicator, and 360 pirouette base.',
                'tags' => ['Home', 'Kitchen', 'Kettle', 'Philips', 'Appliance'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'HOM-005',
                'barcode' => '8850123456916',
                'name' => 'Philips Series 1000 Fabric Shaver Pill Defuzzer',
                'category_code' => 'CAT-HOM',
                'brand_code' => 'BR-PHILIPS',
                'unit_code' => 'PCS',
                'cost_price' => 8.20,
                'selling_price' => 16.50,
                'wholesale_price' => 11.50,
                'vip_price' => 14.00,
                'member_price' => 14.90,
                'online_price' => 16.50,
                'opening_stock' => 40,
                'min_stock' => 6,
                'reorder_level' => 10,
                'image_url' => 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Quickly restores sweaters, blankets, and upholstery fabrics to look like new',
                'description' => '8800 rpm high rotation blade with 3 hole sizes mesh to tackle all pill sizes without fabric damage.',
                'tags' => ['Home', 'Appliance', 'Fabric Shaver', 'Philips'],
                'is_featured' => false,
                'is_new' => true,
            ],

            // --- Apparel & Lifestyle (52 to 55) ---
            [
                'sku' => 'APP-002',
                'barcode' => '8850123456881',
                'name' => 'Nike Dri-FIT Legend Mens Training Athletic T-Shirt (Black)',
                'category_code' => 'CAT-APP',
                'brand_code' => 'BR-NIKE',
                'unit_code' => 'PCS',
                'cost_price' => 14.00,
                'selling_price' => 28.00,
                'wholesale_price' => 19.50,
                'vip_price' => 24.50,
                'member_price' => 26.00,
                'online_price' => 28.00,
                'opening_stock' => 60,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Moisture-wicking breathable fabric with odor-resistant antimicrobial finish',
                'description' => 'Engineered for gym workouts, running, and casual sport. 100% lightweight recycled polyester.',
                'tags' => ['Apparel', 'Sportswear', 'Nike', 'T-Shirt', 'Dri-FIT'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'APP-003',
                'barcode' => '8850123456882',
                'name' => 'Nike Sportswear Heritage86 Adjustable Cap (Midnight Navy)',
                'category_code' => 'CAT-APP',
                'brand_code' => 'BR-NIKE',
                'unit_code' => 'PCS',
                'cost_price' => 11.50,
                'selling_price' => 24.00,
                'wholesale_price' => 16.50,
                'vip_price' => 20.50,
                'member_price' => 22.00,
                'online_price' => 24.00,
                'opening_stock' => 45,
                'min_stock' => 8,
                'reorder_level' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Classic 6-panel twill cap with embroidered swoosh and brass buckle closure',
                'description' => 'Washed cotton twill feels soft and comfortable all day long with embroidered eyelets for breathability.',
                'tags' => ['Apparel', 'Cap', 'Nike', 'Accessories', 'Headwear'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'APP-004',
                'barcode' => '8850123456883',
                'name' => 'Adidas Essentials 3-Stripes Fleece Hoodie (Heather Grey)',
                'category_code' => 'CAT-APP',
                'brand_code' => 'BR-ADIDAS',
                'unit_code' => 'PCS',
                'cost_price' => 28.00,
                'selling_price' => 55.00,
                'wholesale_price' => 38.00,
                'vip_price' => 48.00,
                'member_price' => 50.00,
                'online_price' => 55.00,
                'opening_stock' => 40,
                'min_stock' => 6,
                'reorder_level' => 10,
                'image_url' => 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Ultra-soft cozy cotton-blend fleece hoodie with iconic 3-stripes sleeve detailing',
                'description' => 'Kangaroo pocket, drawcord-adjustable hood, and ribbed cuffs. Sustainable cotton farming partner.',
                'tags' => ['Apparel', 'Hoodie', 'Adidas', 'Sportswear', 'Fleece'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'APP-005',
                'barcode' => '8850123456884',
                'name' => 'Adidas Originals Trefoil Crew Socks (3-Pack White)',
                'category_code' => 'CAT-APP',
                'brand_code' => 'BR-ADIDAS',
                'unit_code' => 'PCK',
                'cost_price' => 6.50,
                'selling_price' => 14.00,
                'wholesale_price' => 9.50,
                'vip_price' => 12.00,
                'member_price' => 13.00,
                'online_price' => 14.00,
                'opening_stock' => 70,
                'min_stock' => 12,
                'reorder_level' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1582965372481-6202476d0d57?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Classic ribbed crew socks with engineered arch compression and cushioning',
                'description' => 'Soft cushioned sole with iconic knit-in Trefoil logo and 3-stripes cuffs.',
                'tags' => ['Apparel', 'Socks', 'Adidas', '3-Pack'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'APP-006',
                'barcode' => '8850123456917',
                'name' => 'Nike Brasilia 9.5 Training Duffel Bag Medium 60L (Black)',
                'category_code' => 'CAT-APP',
                'brand_code' => 'BR-NIKE',
                'unit_code' => 'PCS',
                'cost_price' => 22.00,
                'selling_price' => 45.00,
                'wholesale_price' => 31.00,
                'vip_price' => 39.00,
                'member_price' => 41.00,
                'online_price' => 45.00,
                'opening_stock' => 30,
                'min_stock' => 5,
                'reorder_level' => 8,
                'image_url' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Spacious gym duffel bag with separated ventilated shoe compartment',
                'description' => 'Durable water-resistant coating bottom panel protects contents from gym floors and damp fields.',
                'tags' => ['Apparel', 'Bag', 'Nike', 'Gym', 'Duffel Bag'],
                'is_featured' => true,
                'is_new' => false,
            ],

            // --- Stationery & Office Supplies (56 to 60) ---
            [
                'sku' => 'OFF-001',
                'barcode' => '8850123456891',
                'name' => 'Moleskine Classic Hardcover Notebook Large (Ruled / Black)',
                'category_code' => 'CAT-OFF',
                'brand_code' => 'BR-MOLESKINE',
                'unit_code' => 'PCS',
                'cost_price' => 11.00,
                'selling_price' => 22.50,
                'wholesale_price' => 15.50,
                'vip_price' => 19.50,
                'member_price' => 20.50,
                'online_price' => 22.50,
                'opening_stock' => 50,
                'min_stock' => 8,
                'reorder_level' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Legendary 240-page acid-free ivory paper notebook with elastic closure and bookmark',
                'description' => 'Rounded corners, expandable inner pocket for loose notes, and lies perfectly flat when opened 180 degrees.',
                'tags' => ['Stationery', 'Notebook', 'Moleskine', 'Office', 'Journal'],
                'is_featured' => true,
                'is_new' => false,
            ],
            [
                'sku' => 'OFF-002',
                'barcode' => '8850123456892',
                'name' => 'Moleskine Classic Softcover Dot Grid Notebook Large (Sapphire Blue)',
                'category_code' => 'CAT-OFF',
                'brand_code' => 'BR-MOLESKINE',
                'unit_code' => 'PCS',
                'cost_price' => 11.00,
                'selling_price' => 22.50,
                'wholesale_price' => 15.50,
                'vip_price' => 19.50,
                'member_price' => 20.50,
                'online_price' => 22.50,
                'opening_stock' => 45,
                'min_stock' => 8,
                'reorder_level' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Flexible dot-grid layout notebook optimized for bullet journaling and sketching',
                'description' => 'Smooth ivory 70 gsm paper suitable for fountain pens, rollerballs, and technical drawing pencils.',
                'tags' => ['Stationery', 'Notebook', 'Dot Grid', 'Moleskine'],
                'is_featured' => false,
                'is_new' => true,
            ],
            [
                'sku' => 'OFF-003',
                'barcode' => '8850123456893',
                'name' => 'Moleskine Roller Gel Pen 0.7mm Refillable Matte Metal (Black Ink)',
                'category_code' => 'CAT-OFF',
                'brand_code' => 'BR-MOLESKINE',
                'unit_code' => 'PCS',
                'cost_price' => 6.80,
                'selling_price' => 13.90,
                'wholesale_price' => 9.50,
                'vip_price' => 12.00,
                'member_price' => 12.80,
                'online_price' => 13.90,
                'opening_stock' => 60,
                'min_stock' => 10,
                'reorder_level' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1585336261026-7f41f71dfc88?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Rectangular metal barrel pen designed to clip seamlessly onto hardcover notebooks',
                'description' => 'Glides effortlessly across ivory paper with dark, quick-drying smudge-free black gel ink.',
                'tags' => ['Stationery', 'Pen', 'Gel Pen', 'Moleskine'],
                'is_featured' => false,
                'is_new' => false,
            ],
            [
                'sku' => 'OFF-004',
                'barcode' => '8850123456918',
                'name' => 'Moleskine 12-Month Daily Planner 2026 Pocket (Scarlet Red)',
                'category_code' => 'CAT-OFF',
                'brand_code' => 'BR-MOLESKINE',
                'unit_code' => 'PCS',
                'cost_price' => 9.50,
                'selling_price' => 19.50,
                'wholesale_price' => 13.50,
                'vip_price' => 17.00,
                'member_price' => 18.00,
                'online_price' => 19.50,
                'opening_stock' => 35,
                'min_stock' => 5,
                'reorder_level' => 8,
                'image_url' => 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Full calendar year one page per day agenda planner with ribbon bookmark',
                'description' => 'Structured hourly breakdown from 8 AM to 8 PM with time zones, flight duration tables, and monthly overviews.',
                'tags' => ['Stationery', 'Planner', 'Diary', 'Moleskine', '2026'],
                'is_featured' => false,
                'is_new' => true,
            ],
            [
                'sku' => 'OFF-005',
                'barcode' => '8850123456919',
                'name' => 'Logitech C920x HD Pro Webcam 1080p with Dual Stereo Mics',
                'category_code' => 'CAT-OFF',
                'brand_code' => 'BR-LOGITECH',
                'unit_code' => 'PCS',
                'cost_price' => 45.00,
                'selling_price' => 79.00,
                'wholesale_price' => 58.00,
                'vip_price' => 69.00,
                'member_price' => 72.00,
                'online_price' => 79.00,
                'opening_stock' => 25,
                'min_stock' => 4,
                'reorder_level' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
                'short_description' => 'Full HD 1080p video calling at 30 fps with automatic HD light correction',
                'description' => 'Full HD five-element glass lens captures razor-sharp images while two omni-directional mics record clear stereo audio.',
                'tags' => ['Electronics', 'Webcam', 'Logitech', 'Video Conference', 'Office'],
                'is_featured' => true,
                'is_new' => false,
            ],
        ];

        // 5. Seed Products & Stock
        $createdCount = 0;
        foreach ($products as $pData) {
            $cat = $categories[$pData['category_code']] ?? null;
            $br = $brands[$pData['brand_code']] ?? null;
            $un = $units[$pData['unit_code']] ?? null;

            $stockQty = $pData['opening_stock'];

            $productAttributes = [
                'sku' => $pData['sku'],
                'barcode' => $pData['barcode'],
                'name' => $pData['name'],
                'product_type' => 'SIMPLE',
                'category_id' => $cat?->id,
                'brand_id' => $br?->id,
                'unit_id' => $un?->id ?? 1,
                'cost_price' => $pData['cost_price'],
                'selling_price' => $pData['selling_price'],
                'wholesale_price' => $pData['wholesale_price'],
                'vip_price' => $pData['vip_price'],
                'member_price' => $pData['member_price'],
                'online_price' => $pData['online_price'],
                'tax_rate' => 0.10,
                'opening_stock' => $stockQty,
                'min_stock' => $pData['min_stock'] ?? 10,
                'max_stock' => $stockQty * 3,
                'safety_stock' => $pData['min_stock'] ?? 10,
                'reorder_level' => $pData['reorder_level'] ?? 15,
                'reorder_quantity' => ($pData['min_stock'] ?? 10) * 2,
                'description' => $pData['description'],
                'short_description' => $pData['short_description'],
                'image_url' => $pData['image_url'],
                'tags' => $pData['tags'],
                'is_featured' => $pData['is_featured'],
                'is_new' => $pData['is_new'],
                'visibility' => ['POS', 'WEBSITE', 'MOBILE_APP', 'WHOLESALE'],
                'status_id' => $activeStatusId,
            ];

            $product = Product::updateOrCreate(
                ['sku' => $pData['sku']],
                $productAttributes
            );

            // Create Primary Barcode record
            ProductBarcode::firstOrCreate(
                ['barcode' => $pData['barcode']],
                [
                    'product_id' => $product->id,
                    'barcode_type' => 'EAN_13',
                    'package_type' => 'SINGLE',
                    'multiplier' => 1,
                    'custom_price' => $pData['selling_price'],
                    'is_primary' => true,
                    'notes' => 'Primary Retail Unit Barcode',
                ]
            );

            // Create Warehouse Inventory Stock
            if ($warehouse) {
                Stock::updateOrCreate(
                    ['warehouse_id' => $warehouse->id, 'product_id' => $product->id],
                    [
                        'quantity' => $stockQty,
                        'reserved_quantity' => 0,
                        'available_quantity' => $stockQty,
                        'reorder_level' => $pData['reorder_level'] ?? 15,
                    ]
                );
            }

            $createdCount++;
        }

        $this->command?->info("Successfully seeded/updated {$createdCount} products in catalog!");
    }
}
